title: bhavesh-g
author: Bhavesh G
email: your-email@example.com
description: developer blog
url: "https://bhavesh-g.github.io"
baseurl: ""

# Theme configuration
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how dates are formatted
  show_description: true # show blog description in home page

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - setup-jekyll.sh
